export const epData = {

  // ─── CAST NYLON SHEET ────────────────────────────────────────────────────────
  'cast-nylon-sheet': {
    title: 'Cast Nylon Sheet',
    subtitle: 'Nylon 6 Cast Sheet',
    category: 'Cast Nylon',
    sku: 'VG-NY-SHT',
    mpn: 'VG-NY-SHT',
    image: '/cast_nylon_sheet.png',
    imageAlt: 'Cast Nylon Sheet supplier India - Visanix Global',
    heroDescription: 'Cast nylon (PA6) sheets with high wear resistance, self-lubrication, and excellent dimensional stability. Produced via direct polymerisation for superior mechanical properties over extruded grades.',
    metaTitle: 'Cast Nylon Sheet Supplier India | PA6 Sheet | Visanix Global',
    metaDescription: 'Buy cast nylon (PA6) sheets from Visanix Global, Delhi NCR. High wear resistance, self-lubricating. Sizes: 1ft×1ft, 1mtr×1mtr, 1mtr×2mtr. Thickness 3mm–100mm.',
    specs: [
      { label: 'Standard Sizes', value: '1ft×1ft, 1mtr×1mtr, 1mtr×2mtr' },
      { label: 'Thickness Range', value: '3mm – 100mm' },
      { label: 'Colour', value: 'Cream, Green, Blue, Black' },
      { label: 'Grade', value: 'Cast Nylon 6 (PA6)' },
      { label: 'Custom Sizes', value: 'Available on request' },
    ],
    descriptionPoints: [
      { icon: '💪', heading: 'Superior Molecular Structure', text: 'Cast nylon is produced by direct polymerisation of caprolactam — the polymer is never melted, eliminating thermal degradation. Molecular weight up to 10,00,000 vs 30,000 in extruded grades.' },
      { icon: '🔵', heading: 'Self-Lubricating', text: 'Oil-filled (PA6G) grades contain internal lubricant that migrates to the surface during operation, reducing friction and extending service life in dry-running bearing and gear applications.' },
      { icon: '⚙️', heading: 'Excellent Machinability', text: 'Machines cleanly on standard CNC equipment. Higher tensile and compressive strength, greater hardness, and better dimensional stability than extruded nylon.' },
      { icon: '🌡️', heading: 'Wear & Temperature Resistant', text: 'Higher wear resistance, lower distortion at elevated temperatures, and lower moisture absorption compared to extruded Nylon 6. Suitable for bearings, gears, and structural applications.' },
    ],
    applications: ['Synthetic Ice Rinks', 'Nylon Blocks & Wear Plates', 'Gears & Sprockets', 'Bearing Pads', 'Conveyor Components', 'Food Processing Equipment'],
    faqs: [
      { q: 'What sizes are available for cast nylon sheet?', a: 'Standard sizes are 1ft×1ft, 1mtr×1mtr, and 1mtr×2mtr in thickness from 3mm to 100mm. Custom sizes available on request.' },
      { q: 'What colours does cast nylon sheet come in?', a: 'Available in Cream (standard), Green, Blue (oil-filled), and Black.' },
      { q: 'What is the difference between cast nylon and extruded nylon?', a: 'Cast nylon (PA6) is manufactured by direct polymerisation, giving it higher molecular weight, better mechanical properties, lower moisture absorption, and superior machinability compared to extruded nylon.' },
    ],
  },

  // ─── CAST NYLON ROD ──────────────────────────────────────────────────────────
  'cast-nylon-rod': {
    title: 'Cast Nylon Rod',
    subtitle: 'Nylon 6 Cast Rod',
    category: 'Cast Nylon',
    sku: 'VG-NY-ROD',
    mpn: 'VG-NY-ROD',
    image: '/cast_nylon_rod.png',
    imageAlt: 'Cast Nylon Rod supplier India - Visanix Global',
    heroDescription: 'Cast nylon (PA6) rods for machining into precision bushes, bearings, gears, and custom wear components. High abrasion resistance and temperature resistance for demanding industrial applications.',
    metaTitle: 'Cast Nylon Rod Supplier India | PA6 Nylon Rod | Visanix Global',
    metaDescription: 'Buy cast nylon (PA6) rods from Visanix Global, Delhi NCR. Lengths 300mm, 500mm, 1mtr. Diameter 15mm–450mm. High abrasion and temperature resistance.',
    specs: [
      { label: 'Standard Lengths', value: '300mm, 500mm, 1mtr' },
      { label: 'Diameter Range', value: '15mm – 50mm & 55mm – 450mm' },
      { label: 'Colour', value: 'Cream' },
      { label: 'Grade', value: 'Cast Nylon 6 (PA6)' },
      { label: 'Custom Sizes', value: 'Available on request' },
    ],
    descriptionPoints: [
      { icon: '🔧', heading: 'Precision Machining Blank', text: 'Cast nylon rods are the standard blank for turning custom bushes, bearings, rollers, and gear blanks on CNC lathes.' },
      { icon: '🛡️', heading: 'High Abrasion Resistance', text: 'Superior wear resistance compared to extruded nylon. Can be machined and processed according to specific technical and mechanical requirements.' },
      { icon: '⚖️', heading: 'Lightweight vs Metal', text: 'Nylon components weigh roughly one-eighth of equivalent steel parts, reducing moving mass in rotating and reciprocating machinery.' },
      { icon: '🌡️', heading: 'High Temperature Resistant', text: 'Maintains mechanical properties at elevated temperatures. Suitable for applications requiring both abrasion and temperature resistance.' },
    ],
    applications: ['Bushes & Bearings', 'Gear Blanks', 'Custom Rollers', 'Wear Inserts', 'Structural Components', 'Industrial Machinery Parts'],
    faqs: [
      { q: 'What diameter range do you supply for cast nylon rods?', a: 'We supply cast nylon rods from 15mm to 50mm and 55mm to 450mm diameter. Standard lengths are 300mm, 500mm, and 1mtr.' },
      { q: 'Can cast nylon rods be machined into custom components?', a: 'Yes. Cast nylon rods can be produced and machined according to your technical and mechanical requirements for specific product applications.' },
    ],
  },

  // ─── NYLON ROD (EXTRUDED) ────────────────────────────────────────────────────
  'nylon-rod': {
    title: 'Nylon Square Rod',
    subtitle: 'Nylon Square Bar',
    category: 'Cast Nylon',
    sku: 'VG-NY-SQR',
    mpn: 'VG-NY-SQR',
    image: '/NYLON_Square_Rod.png',
    imageAlt: 'Nylon Square Rod supplier India - Visanix Global',
    heroDescription: 'Nylon square rods with improved coefficient of friction, consistent wear performance, and excellent mechanical, thermal, and chemical resistance. Ideal for guide rails, wear strips, and structural components.',
    metaTitle: 'Nylon Square Rod Supplier India | Nylon Square Bar | Visanix Global',
    metaDescription: 'Buy nylon square rods from Visanix Global, Delhi NCR. Length 1mtr. Diameter 20mm–200mm. Cream colour. Excellent wear performance and reduced water absorption.',
    specs: [
      { label: 'Standard Length', value: '1mtr' },
      { label: 'Section Range', value: '20mm – 200mm' },
      { label: 'Colour', value: 'Cream' },
      { label: 'Properties', value: 'Reduced water absorption, low friction' },
      { label: 'Custom Sizes', value: 'Available on request' },
    ],
    descriptionPoints: [
      { icon: '📐', heading: 'Improved Friction Characteristics', text: 'Improved coefficient of friction and stick-slip characteristics compared to standard nylon. Consistent wear performance throughout product life.' },
      { icon: '💧', heading: 'Reduced Water Absorption', text: 'Lower moisture uptake than standard cast nylon, maintaining dimensional stability in humid and wet environments.' },
      { icon: '🔩', heading: 'Flat-Face Machining', text: 'Square section provides stable flat faces for milling wear blocks, guide rails, and structural pads without additional fixturing.' },
      { icon: '🧪', heading: 'Chemical Resistance', text: 'Excellent mechanical, thermal, and chemical resistance properties suitable for a wide range of industrial environments.' },
    ],
    applications: ['Guide Rails', 'Wear Strips', 'Slide Pads', 'Structural Components', 'Machine Gibs', 'Spacers & Shims'],
    faqs: [
      { q: 'What section sizes do you supply for nylon square rod?', a: 'Standard sections from 20mm to 200mm in 1mtr lengths. Custom sizes available on request.' },
      { q: 'How does nylon square rod compare to round rod?', a: 'Square rod provides flat faces that are easier to clamp and machine for flat-face wear and structural components without additional fixturing.' },
    ],
  },

  // ─── PVC SHEET ───────────────────────────────────────────────────────────────
  'pvc-sheet': {
    title: 'PVC Sheet',
    subtitle: 'Rigid PVC Sheet (uPVC)',
    category: 'PVC',
    sku: 'VG-PVC-SHT',
    mpn: 'VG-PVC-SHT',
    image: '/PVC_Rigid_sheet.png',
    imageAlt: 'Rigid PVC Sheet supplier India - Visanix Global',
    heroDescription: 'Rigid PVC sheets for chemical tank fabrication, electroplating equipment, ductwork, and general-purpose corrosion-resistant construction. Weldable with standard hot-air welding equipment.',
    metaTitle: 'PVC Sheet Supplier India | Rigid uPVC Sheet | Visanix Global',
    metaDescription: 'Buy rigid PVC (uPVC) sheets from Visanix Global, Delhi NCR. Size 4ft×8ft. Thickness 1mm–30mm. Dark grey. For chemical tanks, ducting, and electroplating equipment.',
    specs: [
      { label: 'Standard Size', value: '4ft × 8ft' },
      { label: 'Thickness Range', value: '1mm – 30mm' },
      { label: 'Colour', value: 'Dark Grey' },
      { label: 'Grade', value: 'Rigid uPVC (unplasticised)' },
      { label: 'Custom Sizes', value: 'Available on request' },
    ],
    descriptionPoints: [
      { icon: '🧪', heading: 'Chemical Resistance', text: 'Rigid PVC resists most inorganic acids, alkalis, and salt solutions. The established standard material for chemical ductwork, tank fabrication, and plating equipment.' },
      { icon: '🔥', heading: 'Weldable', text: 'PVC welds cleanly using hot-air and hot-wedge welding, enabling fabrication of chemically resistant tanks, ducting, and vessel linings.' },
      { icon: '💰', heading: 'Cost-Effective', text: 'One of the most cost-effective engineering plastics per unit volume, widely available and easy to fabricate.' },
      { icon: '🔇', heading: 'Sound Insulation', text: 'High damping characteristics make PVC suitable for acoustic enclosures and noise-reduction ductwork in industrial extraction systems.' },
    ],
    applications: ['Chemical Storage Tanks', 'Acid Duct Fabrication', 'Electroplating Tanks', 'Fume Hoods', 'Pipe & Fitting Lining', 'Structural Panels'],
    faqs: [
      { q: 'What size and thickness is PVC sheet available in?', a: 'Standard size is 4ft×8ft in thickness from 1mm to 30mm. Dark grey colour. Custom sizes available on request.' },
      { q: 'Can PVC sheets be welded to fabricate chemical tanks?', a: 'Yes. Rigid PVC sheets are routinely welded using hot-air or hot-wedge techniques to fabricate chemical storage tanks, acid baths, and process equipment.' },
    ],
  },

  // ─── PP SHEET ─────────────────────────────────────────────────────────────────
  'pp-sheet': {
    title: 'Polypropylene Sheet',
    subtitle: 'PP Sheet',
    category: 'Polypropylene (PP)',
    sku: 'VG-PP-SHT',
    mpn: 'VG-PP-SHT',
    image: '/ptfe-sheets-moulded.jpg',
    imageAlt: 'Polypropylene PP Sheet supplier India - Visanix Global',
    heroDescription: 'Polypropylene sheets for chemical tank fabrication, plating tanks, semiconductor equipment, and food processing applications. Lightweight with broad chemical resistance.',
    metaTitle: 'Polypropylene Sheet Supplier India | PP Sheet | Visanix Global',
    metaDescription: 'Buy polypropylene (PP) sheets from Visanix Global, Delhi NCR. Sizes: 1mtr×2mtr, 1200mm×2mtr, 4ft×8ft, 1mtr×4mtr. Thickness 1mm–100mm. White colour.',
    specs: [
      { label: 'Standard Sizes', value: '1mtr×2mtr, 1200mm×2mtr, 4ft×8ft, 1mtr×4mtr' },
      { label: 'Thickness Range', value: '1mm – 100mm' },
      { label: 'Colour', value: 'White' },
      { label: 'Grade', value: 'PP Homopolymer' },
      { label: 'Custom Sizes', value: 'Available on request' },
    ],
    descriptionPoints: [
      { icon: '🧪', heading: 'Broad Chemical Resistance', text: 'PP resists most inorganic acids, alkalis, and solvents. Used for chemical tanks, plating tanks, fire truck water tanks (copolymer), and semiconductor equipment cabinets.' },
      { icon: '🔥', heading: 'Weldable', text: 'PP sheets weld cleanly using hot-air and extrusion welding, enabling fabrication of chemical storage tanks, ducting, and vessel linings.' },
      { icon: '⚖️', heading: 'Lightweight', text: 'Roughly half the density of PVC with comparable chemical resistance, reducing structural weight in large fabricated components.' },
      { icon: '🍽️', heading: 'Food Grade Available', text: 'Suitable for cutting boards for food preparation and food processing equipment. Complies with food contact regulations.' },
    ],
    applications: ['Chemical Tanks', 'Plating Tanks', 'Semiconductor Equipment', 'Cutting Boards', 'Food Processing', 'Duct Fabrication'],
    faqs: [
      { q: 'What sizes are PP sheets available in?', a: 'Standard sizes are 1mtr×2mtr, 1200mm×2mtr, 4ft×8ft, and 1mtr×4mtr in thickness from 1mm to 100mm, white colour.' },
      { q: 'What chemical resistance does polypropylene sheet offer?', a: 'PP resists most inorganic acids, alkalis, salts, and many organic solvents at ambient temperature. Not recommended for strongly oxidising acids or halogenated solvents.' },
    ],
  },

  // ─── PP ROD ───────────────────────────────────────────────────────────────────
  'pp-rod': {
    title: 'Polypropylene Rod',
    subtitle: 'PP Rod',
    category: 'Polypropylene (PP)',
    sku: 'VG-PP-ROD',
    mpn: 'VG-PP-ROD',
    image: '/ptfe-rod-hd.jpg',
    imageAlt: 'Polypropylene PP Rod supplier India - Visanix Global',
    heroDescription: 'Polypropylene rods for machining chemical plant components, pump parts, and fittings. Excellent tensile strength and corrosion resistance for demanding industrial environments.',
    metaTitle: 'Polypropylene Rod Supplier India | PP Rod | Visanix Global',
    metaDescription: 'Buy polypropylene (PP) rods from Visanix Global, Delhi NCR. Lengths 300mm, 1mtr, 2mtr. Diameter 1mm–100mm. White colour. For chemical plant and pump components.',
    specs: [
      { label: 'Standard Lengths', value: '300mm, 1mtr, 2mtr' },
      { label: 'Diameter Range', value: '1mm – 100mm' },
      { label: 'Colour', value: 'White' },
      { label: 'Grade', value: 'PP Homopolymer' },
      { label: 'Custom Sizes', value: 'Available on request' },
    ],
    descriptionPoints: [
      { icon: '🧪', heading: 'High Corrosion Resistance', text: 'Excellent resistance to organic solvents, degreasing agents, and electrolytic attack. Used for chemical tanks, plating tanks, and semiconductor work surfaces.' },
      { icon: '⚙️', heading: 'Tensile Strength at Temperature', text: 'Homopolymer PP is harder with excellent tensile strength and stiffness at elevated temperatures.' },
      { icon: '🍽️', heading: 'Food Safe', text: 'Natural grade PP is food-safe. Widely used for cutting boards and food preparation equipment machined components.' },
      { icon: '📐', heading: 'Wide Diameter Range', text: 'Available from 1mm to 100mm diameter in standard lengths of 300mm, 1mtr, and 2mtr.' },
    ],
    applications: ['Pump Components', 'Valve Parts', 'Chemical Fittings', 'Food Processing Parts', 'Semiconductor Equipment', 'Plating Tank Components'],
    faqs: [
      { q: 'What diameter range do you supply for PP rods?', a: 'Standard PP rods from 1mm to 100mm diameter in lengths of 300mm, 1mtr, and 2mtr, white colour.' },
    ],
  },

  // ─── PU SHEET ─────────────────────────────────────────────────────────────────
  'pu-sheet': {
    title: 'Polyurethane Sheet',
    subtitle: 'PU Sheet',
    category: 'Polyurethane (PU)',
    sku: 'VG-PU-SHT',
    mpn: 'VG-PU-SHT',
    image: '/PU_Sheet.png',
    imageAlt: 'Polyurethane PU Sheet supplier India - Visanix Global',
    heroDescription: 'Industrial-grade polyurethane sheets for sports equipment, building materials, petroleum, mining, and automobile industries. Used for cushioning pads, die materials, and vibration reduction in heavy machinery.',
    metaTitle: 'Polyurethane Sheet Supplier India | PU Sheet | Visanix Global',
    metaDescription: 'Buy polyurethane (PU) sheets from Visanix Global, Delhi NCR. Sizes: 1ft×1ft, 1mtr×1mtr, 1mtr×4mtr. Thickness 2mm–100mm. Lemon, Green, Yellow colours.',
    specs: [
      { label: 'Standard Sizes', value: '1ft×1ft, 1mtr×1mtr, 1mtr×4mtr' },
      { label: 'Thickness Range', value: '2mm – 100mm' },
      { label: 'Colour', value: 'Lemon, Green, Yellow' },
      { label: 'Custom Sizes', value: 'Available on request' },
    ],
    descriptionPoints: [
      { icon: '🛡️', heading: 'Outstanding Abrasion Resistance', text: 'Polyurethane outperforms rubber and many plastics in sliding and impact abrasion tests — ideal for lining chutes, hoppers, and wear surfaces.' },
      { icon: '⚡', heading: 'Friction & Vibration Reduction', text: 'Used for its friction, vibration reduction, and buffer properties in mechanical equipment. Suitable for cushioning pads, springs, and die materials.' },
      { icon: '🏭', heading: 'Multi-Industry Use', text: 'Applications span sports equipment, building materials, petroleum, mining, and automobile sectors — cushioning pads, metal plates, pipes, and stamping equipment components.' },
      { icon: '✂️', heading: 'Machinable & Fabricable', text: 'PU sheets can be cut, punched, routed, and machined into custom wear parts. Bond well with adhesives for bonded liner applications.' },
    ],
    applications: ['Cushioning Pads', 'Die Materials', 'Stamping Equipment', 'Vibration Dampening', 'Mining Wear Liners', 'Conveyor Skirting', 'Screen Panels'],
    faqs: [
      { q: 'What sizes are PU sheets available in?', a: 'Standard sizes are 1ft×1ft, 1mtr×1mtr, and 1mtr×4mtr in thickness from 2mm to 100mm. Available in Lemon, Green, and Yellow colours.' },
      { q: 'What industries use PU sheets?', a: 'PU sheets are used in sports equipment, building materials, petroleum, mining, and automobile industries for cushioning pads, die materials, and vibration reduction applications.' },
    ],
  },

  // ─── PU ROD ───────────────────────────────────────────────────────────────────
  'pu-rod': {
    title: 'Polyurethane Rod',
    subtitle: 'PU Rod',
    category: 'Polyurethane (PU)',
    sku: 'VG-PU-ROD',
    mpn: 'VG-PU-ROD',
    image: '/PU_Rod.png',
    imageAlt: 'Polyurethane PU Rod supplier India - Visanix Global',
    heroDescription: 'Cast polyurethane rods for machining into custom wear components, bushes, rollers, and buffer elements. Used across sports, building, petroleum, mining, and automobile industries.',
    metaTitle: 'Polyurethane Rod Supplier India | PU Rod | Visanix Global',
    metaDescription: 'Buy polyurethane (PU) rods from Visanix Global, Delhi NCR. Lengths 1ft and 1mtr. Diameter 16mm–200mm. Lemon, Green, Yellow colours.',
    specs: [
      { label: 'Standard Lengths', value: '1ft, 1mtr' },
      { label: 'Diameter Range', value: '16mm – 200mm' },
      { label: 'Colour', value: 'Lemon, Green, Yellow' },
      { label: 'Custom Sizes', value: 'Available on request' },
    ],
    descriptionPoints: [
      { icon: '⚙️', heading: 'Machinable Wear Parts', text: 'PU rods machine into custom wear bushes, rollers, springs, and buffer components for heavy machinery and stamping equipment.' },
      { icon: '🔵', heading: 'Impact & Wear Resistant', text: 'Combines high elasticity with excellent resistance to impact and abrasion — suitable for components subject to repeated dynamic loading.' },
      { icon: '🏭', heading: 'Multi-Industry Applications', text: 'Used in sports equipment, building materials, petroleum, mining, and automobile industries for springs, metal plate protection, and die materials.' },
      { icon: '📐', heading: 'Friction & Buffer Properties', text: 'Deployed for its friction, vibration reduction, and buffer characteristics in mechanical equipment applications.' },
    ],
    applications: ['Wear Bushes', 'Custom Rollers', 'Buffer Components', 'Seal Rings', 'Machine Wear Parts', 'Stamping Equipment Parts'],
    faqs: [
      { q: 'What sizes are PU rods available in?', a: 'Standard PU rods in lengths of 1ft and 1mtr, diameter from 16mm to 200mm. Available in Lemon, Green, and Yellow colours.' },
    ],
  },

  // ─── DELRIN SHEET ────────────────────────────────────────────────────────────
  'delrin-sheet': {
    title: 'Delrin Sheet',
    subtitle: 'POM / Acetal Sheet',
    category: 'Delrin / POM',
    sku: 'VG-POM-SHT',
    mpn: 'VG-POM-SHT',
    image: '/Derlin_Sheet.png',
    imageAlt: 'Delrin POM Acetal Sheet supplier India - Visanix Global',
    heroDescription: 'Delrin (POM/Acetal) sheets ideal for pump and valve components, gears, bearings, bushings, rollers, fittings, and electrical insulator parts — especially in moist or wet environments.',
    metaTitle: 'Delrin Sheet Supplier India | POM Acetal Sheet | Visanix Global',
    metaDescription: 'Buy Delrin (POM/Acetal) sheets from Visanix Global, Delhi NCR. Sizes: 4ft×2ft, 1mtr×2mtr. Thickness 6mm–100mm. Black and White. For gears, bearings, and valve components.',
    specs: [
      { label: 'Standard Sizes', value: '4ft×2ft, 1mtr×2mtr' },
      { label: 'Thickness Range', value: '6mm, 8mm, 10mm, 12mm, 15mm–50mm, 55mm–100mm' },
      { label: 'Colour', value: 'Black, White' },
      { label: 'Grade', value: 'POM-C (Copolymer) / POM-H (Homopolymer)' },
      { label: 'Custom Sizes', value: 'Available on request' },
    ],
    descriptionPoints: [
      { icon: '💧', heading: 'Ideal for Wet Environments', text: 'Parts exposed to a moist or wet environment — pump and valve components — are especially suited to Delrin due to its very low moisture absorption and dimensional stability.' },
      { icon: '📏', heading: 'Exceptional Dimensional Stability', text: 'POM absorbs very little moisture compared to nylon, maintaining dimensional accuracy in humid environments — critical for precision gear and bearing components.' },
      { icon: '⚙️', heading: 'Precise Machinability', text: 'Machines to tight tolerances with excellent surface finish. Ideal for gears, cams, valve components, and precision mechanical parts.' },
      { icon: '⚡', heading: 'Good Electrical Insulation', text: 'Good electrical insulating and dielectric properties make Delrin a suitable choice for electrically insulating components.' },
    ],
    applications: ['Pump & Valve Components', 'Gears', 'Bearings & Bushings', 'Rollers', 'Fittings', 'Electrical Insulator Parts', 'Cams'],
    faqs: [
      { q: 'What sizes are Delrin sheets available in?', a: 'Standard sizes are 4ft×2ft and 1mtr×2mtr. Thickness from 6mm to 100mm (6, 8, 10, 12, 15–50mm and 55–100mm). Available in Black and White.' },
      { q: 'Why is Delrin preferred for wet environment applications?', a: 'Delrin (POM) absorbs far less moisture than nylon, maintaining bore and gear dimensions precisely in wet conditions — making it ideal for pumps, valves, and food machinery.' },
    ],
  },

  // ─── DELRIN ROD ──────────────────────────────────────────────────────────────
  'delrin-rod': {
    title: 'Delrin Rod',
    subtitle: 'POM / Acetal Rod',
    category: 'Delrin / POM',
    sku: 'VG-POM-ROD',
    mpn: 'VG-POM-ROD',
    image: '/Derlin_Rod.png',
    imageAlt: 'Delrin POM Acetal Rod supplier India - Visanix Global',
    heroDescription: 'Delrin (POM/Acetal) rods for precision CNC machining into gear wheels, cams, bearings, rollers, and electrically insulating components. Good dielectric properties alongside excellent mechanical performance.',
    metaTitle: 'Delrin Rod Supplier India | POM Acetal Rod | Visanix Global',
    metaDescription: 'Buy Delrin (POM/Acetal) rods from Visanix Global, Delhi NCR. Lengths 300mm, 1mtr. Diameter 12mm–250mm. Black colour. For gears, cams, bearings, and rollers.',
    specs: [
      { label: 'Standard Lengths', value: '300mm, 1mtr' },
      { label: 'Diameter Range', value: '12mm–16mm, 20mm–150mm, 160mm–250mm' },
      { label: 'Colour', value: 'Black' },
      { label: 'Grade', value: 'POM-C / POM-H' },
      { label: 'Custom Sizes', value: 'Available on request' },
    ],
    descriptionPoints: [
      { icon: '⚙️', heading: 'Precision Gear Blanks', text: 'Commonly used for gear wheels, cams, bearings, and rollers. POM\'s low friction and high stiffness give quiet, accurate gear operation.' },
      { icon: '⚡', heading: 'Electrical Insulation', text: 'Good electrical insulating and dielectric properties make Delrin rod a practical choice for electrically insulating components.' },
      { icon: '📏', heading: 'Tight Tolerance Machining', text: 'POM holds tight tolerances and achieves excellent surface finish without special tooling. Dimensional stability maintained after machining.' },
      { icon: '⚡', heading: 'Fatigue Resistance', text: 'High fatigue endurance makes POM suitable for cyclically loaded components such as cams, springs, and snap-fit assemblies.' },
    ],
    applications: ['Gear Wheels', 'Cams', 'Bearings & Rollers', 'Valve Bodies', 'Electrical Insulator Parts', 'Precision Turned Components'],
    faqs: [
      { q: 'What diameter range do you supply for Delrin rods?', a: 'Standard Delrin rods from 12mm–16mm, 20mm–150mm, and 160mm–250mm diameter. Lengths 300mm and 1mtr. Black colour.' },
      { q: 'Is POM rod suitable for gear cutting?', a: 'Yes. POM is one of the most widely used plastics for hobbed and milled gears due to its combination of stiffness, low friction, quiet operation, and dimensional stability.' },
    ],
  },

  // ─── PEEK SHEET ──────────────────────────────────────────────────────────────
  'peek-sheet': {
    title: 'PEEK Sheet',
    subtitle: 'Polyether Ether Ketone Sheet',
    category: 'PEEK',
    sku: 'VG-PK-SHT',
    mpn: 'VG-PK-SHT',
    image: '/PEEK_Sheet.png',
    imageAlt: 'PEEK Sheet supplier India - Visanix Global',
    heroDescription: 'PEEK sheets for demanding applications including bearings, piston parts, pumps, HPLC columns, compressor plate valves, and cable insulation. One of very few plastics compatible with vacuum applications.',
    metaTitle: 'PEEK Sheet Supplier India | Polyether Ether Ketone Sheet | Visanix Global',
    metaDescription: 'Buy PEEK sheets from Visanix Global, Delhi NCR. Size 620mm×1000mm. Thickness 5mm–120mm. Brown colour. For bearings, pumps, compressor valves, and vacuum applications.',
    specs: [
      { label: 'Standard Size', value: '620mm × 1000mm' },
      { label: 'Thickness Range', value: '5mm – 120mm' },
      { label: 'Colour', value: 'Brown' },
      { label: 'Continuous Service Temp', value: 'Up to 250°C' },
      { label: 'Custom Sizes', value: 'Available on request' },
    ],
    descriptionPoints: [
      { icon: '🌡️', heading: 'Continuous High-Temperature Service', text: 'PEEK operates continuously at up to 250°C — one of the highest service temperatures of any thermoplastic. Full mechanical properties retained at temperature.' },
      { icon: '🔬', heading: 'Vacuum Compatible', text: 'One of very few plastics compatible with vacuum applications. Used in HPLC columns, semiconductor equipment, and precision instrument components.' },
      { icon: '🧪', heading: 'Exceptional Chemical Resistance', text: 'PEEK resists virtually all organic solvents, fuels, and most inorganic acids at elevated temperatures.' },
      { icon: '⚙️', heading: 'Demanding Application Grade', text: 'Used for bearings, piston parts, pumps, compressor plate valves, and cable insulation where other engineering plastics fail.' },
    ],
    applications: ['Bearings', 'Piston Parts', 'Pumps', 'HPLC Columns', 'Compressor Plate Valves', 'Cable Insulation', 'Vacuum Applications'],
    faqs: [
      { q: 'What size and thickness is PEEK sheet available in?', a: 'Standard size is 620mm×1000mm in thickness from 5mm to 120mm, brown colour. Custom sizes available on request.' },
      { q: 'What continuous service temperature does PEEK handle?', a: 'Standard PEEK handles continuous service up to 250°C, retaining full mechanical properties throughout.' },
    ],
  },

  // ─── ACRYLIC ROD ─────────────────────────────────────────────────────────────
  'acrylic-rod': {
    title: 'Acrylic Rod',
    subtitle: 'PMMA / Perspex Rod',
    category: 'Acrylic',
    sku: 'VG-AC-ROD',
    mpn: 'VG-AC-ROD',
    image: '/Acrylic_Rod.png',
    imageAlt: 'Acrylic Rod supplier India - Visanix Global',
    heroDescription: 'Clear acrylic rods for sign holders, crystal chandeliers, office interior objects, skylights, glazing applications, and model making. Transparent with excellent optical finish.',
    metaTitle: 'Acrylic Rod Supplier India | PMMA Clear Rod | Visanix Global',
    metaDescription: 'Buy clear acrylic (PMMA) rods from Visanix Global, Delhi NCR. Lengths 1mtr and 2mtr. Diameter 3mm–200mm. Transparent. For signage, display, and optical applications.',
    specs: [
      { label: 'Standard Lengths', value: '1mtr, 2mtr' },
      { label: 'Diameter Range', value: '3mm – 200mm' },
      { label: 'Colour', value: 'Transparent' },
      { label: 'Surface Finish', value: 'Polished' },
      { label: 'Custom Sizes', value: 'Available on request' },
    ],
    descriptionPoints: [
      { icon: '💡', heading: 'Light Piping & Display', text: 'Acrylic rods transmit light along their length via total internal reflection. Most commonly used for sign holders, crystal chandeliers, and illuminated display elements.' },
      { icon: '🏗️', heading: 'Architectural & Interior Use', text: 'Used in office interior objects, skylights, glazing applications, and model making where transparency and optical finish are important.' },
      { icon: '⚙️', heading: 'Machinable', text: 'Machines cleanly into precision-turned optical and decorative components. Can be polished to restore surface clarity after machining.' },
      { icon: '☀️', heading: 'UV Stable', text: 'Does not yellow with prolonged UV exposure, maintaining optical clarity for long-term outdoor and architectural applications.' },
    ],
    applications: ['Sign Holders', 'Crystal Chandeliers', 'Office Interior Objects', 'Skylights', 'Glazing Applications', 'Model Making', 'Light Pipes'],
    faqs: [
      { q: 'What diameter range do you supply for acrylic rods?', a: 'Standard acrylic rods from 3mm to 200mm diameter in lengths of 1mtr and 2mtr, transparent.' },
      { q: 'Can acrylic rods be used for light piping?', a: 'Yes. Acrylic rods transmit light efficiently along their length via total internal reflection, making them effective light pipes for sign and display applications.' },
    ],
  },

  // ─── EPOXY LAMINATED SHEET ───────────────────────────────────────────────────
  'epoxy-laminated-sheet': {
    title: 'Epoxy Laminated Sheet',
    subtitle: 'FR4 / G10 Epoxy Glass Sheet',
    category: 'Epoxy Laminated',
    sku: 'VG-EP-SHT',
    mpn: 'VG-EP-SHT',
    image: '/placeholder-epoxy-sheet.jpg',
    imageAlt: 'Epoxy Laminated Sheet supplier India - Visanix Global',
    heroDescription: 'Epoxy laminated glass fibre sheets (FR4/G10) offering excellent electrical insulation, high mechanical strength, and good thermal stability. Used in electrical and electronic applications requiring reliable dielectric performance.',
    metaTitle: 'Epoxy Laminated Sheet Supplier India | FR4 G10 Sheet | Visanix Global',
    metaDescription: 'Buy epoxy laminated (FR4/G10) sheets from Visanix Global, Delhi NCR. Excellent electrical insulation and mechanical strength. For PCBs, switchgear, and electrical insulation.',
    specs: [
      { label: 'Grade', value: 'FR4, G10, G11' },
      { label: 'Thickness Range', value: '0.5mm – 100mm' },
      { label: 'Standard Sheet Size', value: '1000×1000mm, 1220×2440mm' },
      { label: 'Colour', value: 'Green (FR4), Natural (G10/G11)' },
      { label: 'Custom Sizes', value: 'Available on request' },
    ],
    descriptionPoints: [
      { icon: '⚡', heading: 'High Electrical Insulation', text: 'Epoxy glass laminates offer outstanding dielectric strength and volume resistivity — the standard insulation material for switchgear, transformers, and electrical panel construction.' },
      { icon: '💪', heading: 'High Mechanical Strength', text: 'Glass fibre reinforcement gives high tensile, flexural, and compressive strength — significantly stronger than unreinforced plastics for structural electrical components.' },
      { icon: '🔥', heading: 'Flame Retardant (FR4)', text: 'FR4 grade meets UL94 V-0 flame retardancy requirements — the standard for PCB substrates and electrical enclosure panels.' },
      { icon: '🌡️', heading: 'Thermal Stability', text: 'Maintains electrical and mechanical properties over a wide temperature range. Suitable for applications involving heat dissipation or elevated operating temperatures.' },
    ],
    applications: ['PCB Substrates', 'Switchgear Insulation', 'Transformer Insulation', 'Electrical Panel Components', 'Busbar Support', 'Motor Insulation', 'Jig & Fixture Plates'],
    faqs: [
      { q: 'What is the difference between FR4 and G10 epoxy laminated sheet?', a: 'FR4 has flame retardant properties (UL94 V-0 rated) and is the standard for PCB substrates and electrical enclosures. G10 is the non-flame-retardant version with slightly higher mechanical and electrical properties, used where flame retardancy is not required.' },
      { q: 'What thickness range is available for epoxy laminated sheet?', a: 'Standard thickness from 0.5mm to 100mm. Sheet sizes 1000×1000mm and 1220×2440mm. Custom sizes available on request.' },
      { q: 'Can epoxy laminated sheets be machined?', a: 'Yes. FR4/G10 sheets machine with carbide tooling. Dust extraction is recommended as the glass fibre reinforcement generates abrasive dust during cutting and drilling.' },
    ],
  },

  // ─── SILICONE SHEET ──────────────────────────────────────────────────────────
  'silicone-sheet': {
    title: 'Silicone Sheet',
    subtitle: 'Food Grade & Industrial Silicone Sheet',
    category: 'Silicone',
    sku: 'VG-SIL-SHT',
    mpn: 'VG-SIL-SHT',
    image: '/Silicon_Sheet.png',
    imageAlt: 'Silicone Sheet supplier India - Visanix Global',
    heroDescription: 'Industrial and food-grade silicone sheets with exceptional thermal stability, flexibility across extreme temperature ranges, and FDA compliance. Used for gaskets, seals, and food processing components.',
    metaTitle: 'Silicone Sheet Supplier India | Food Grade Silicone Sheet | Visanix Global',
    metaDescription: 'Buy silicone sheets from Visanix Global, Delhi NCR. Temperature range -60°C to +230°C. Red, Blue, White, Transparent. For gaskets, seals, and food processing.',
    specs: [
      { label: 'Thickness Range', value: '0.5mm – 50mm' },
      { label: 'Standard Sheet Size', value: '1000×1000mm, 1200×600mm' },
      { label: 'Temperature Range', value: '-60°C to +230°C' },
      { label: 'Colour', value: 'Red, Blue, White, Transparent' },
      { label: 'Grade', value: 'Food Grade (FDA), Industrial' },
    ],
    descriptionPoints: [
      { icon: '🌡️', heading: 'Extreme Temperature Range', text: 'Silicone retains flexibility and sealing performance from -60°C to +230°C — one of the widest service temperature ranges of any elastomeric sheet material.' },
      { icon: '🍽️', heading: 'FDA Food Grade', text: 'Food-grade silicone complies with FDA 21 CFR 177.2600 and EU food contact regulations. Widely used in food processing, pharmaceutical, and medical applications.' },
      { icon: '⚡', heading: 'Electrical Insulation', text: 'Excellent dielectric properties across a wide frequency and temperature range. Used for electrical insulation gaskets and sealing in high-temperature enclosures.' },
      { icon: '🧪', heading: 'Ozone & UV Resistant', text: 'Silicone does not degrade with exposure to ozone, UV radiation, or weathering — suitable for outdoor and long-life sealing applications.' },
    ],
    applications: ['Food Processing Gaskets', 'Pharmaceutical Seals', 'Electrical Insulation', 'Oven Door Seals', 'High-Temperature Gaskets', 'Medical Device Components', 'Vibration Dampening Pads'],
    faqs: [
      { q: 'What temperature range does silicone sheet handle?', a: 'Silicone sheet operates from -60°C to +230°C, retaining flexibility and sealing performance across this range.' },
      { q: 'Is silicone sheet food safe?', a: 'Yes. Food-grade silicone complies with FDA 21 CFR 177.2600 and is widely used in food processing, pharmaceutical, and medical contact applications.' },
      { q: 'What colours is silicone sheet available in?', a: 'Available in Red, Blue, White, and Transparent. Food-grade grades are typically Red or Translucent.' },
    ],
  },

  // ─── SILICONE TUBE ───────────────────────────────────────────────────────────
  'silicone-tube': {
    title: 'Silicone Tube',
    subtitle: 'Food Grade & Industrial Silicone Tubing',
    category: 'Silicone',
    sku: 'VG-SIL-TUB',
    mpn: 'VG-SIL-TUB',
    image: '/Silicon_Rubber_Tube.png',
    imageAlt: 'Silicone Tube supplier India - Visanix Global',
    heroDescription: 'Food-grade and industrial silicone tubes for fluid transfer, pharmaceutical processing, peristaltic pumps, and high-temperature fluid lines. Flexible across the full temperature range.',
    metaTitle: 'Silicone Tube Supplier India | Food Grade Silicone Tubing | Visanix Global',
    metaDescription: 'Buy silicone tubes from Visanix Global, Delhi NCR. Full OD/ID range. Temperature -60°C to +230°C. Red, Transparent. For food, pharma, and peristaltic pump applications.',
    specs: [
      { label: 'OD Range', value: 'Full range — price list on request' },
      { label: 'Temperature Range', value: '-60°C to +230°C' },
      { label: 'Colour', value: 'Red, Transparent' },
      { label: 'Grade', value: 'Food Grade (FDA), Industrial' },
      { label: 'Supply Form', value: 'Coils or straight lengths' },
    ],
    descriptionPoints: [
      { icon: '💧', heading: 'Food & Pharma Fluid Transfer', text: 'FDA-compliant silicone tubing is the standard for peristaltic pump lines, pharmaceutical fluid transfer, and food processing piping where purity and flexibility are required.' },
      { icon: '🌡️', heading: 'Wide Temperature Range', text: 'Maintains flexibility and sealing performance from -60°C to +230°C. Does not become brittle at low temperatures or soften excessively at high temperatures.' },
      { icon: '🔬', heading: 'Non-Toxic & Odourless', text: 'Silicone is non-toxic, odourless, and tasteless — will not contaminate food, beverages, or pharmaceutical products passing through the tube.' },
      { icon: '🧪', heading: 'Ozone & UV Resistant', text: 'Excellent resistance to ozone, UV, and weathering. Suitable for outdoor fluid lines and long-life installations.' },
    ],
    applications: ['Peristaltic Pump Lines', 'Food Processing Fluid Transfer', 'Pharmaceutical Piping', 'Laboratory Tubing', 'High-Temperature Fluid Lines', 'Medical Device Tubing'],
    faqs: [
      { q: 'What OD/ID range do you supply for silicone tubes?', a: 'We supply silicone tubes in a full range of OD and ID sizes. Contact us with your specification for pricing and availability.' },
      { q: 'Is silicone tubing suitable for peristaltic pump applications?', a: 'Yes. Silicone tubing is the standard choice for peristaltic pumps due to its flexibility, chemical inertness, and ability to withstand repeated compression without fatigue.' },
      { q: 'What colours are silicone tubes available in?', a: 'Available in Red and Transparent. Custom colours available on request.' },
    ],
  },

  // ─── INSULATION ROD ──────────────────────────────────────────────────────────
  'insulation-rod': {
    title: 'Insulation Rod',
    subtitle: 'Bakelite / Epoxy / Resin Insulation Rod',
    category: 'Insulation Materials',
    sku: 'VG-INS-ROD',
    mpn: 'VG-INS-ROD',
    image: '/placeholder-insulation-rod.jpg',
    imageAlt: 'Insulation Rod supplier India - Visanix Global',
    heroDescription: 'Electrical insulation rods in bakelite, epoxy resin, and phenolic grades for switchgear, transformer supports, busbar insulators, and electrical equipment structural components.',
    metaTitle: 'Insulation Rod Supplier India | Bakelite Epoxy Insulation Rod | Visanix Global',
    metaDescription: 'Buy insulation rods from Visanix Global, Delhi NCR. Bakelite, epoxy, and phenolic grades. For switchgear, transformers, and busbar insulation. Custom diameters and lengths.',
    specs: [
      { label: 'Grade', value: 'Bakelite, Epoxy (FR4/G10), Phenolic' },
      { label: 'Diameter Range', value: '6mm – 200mm' },
      { label: 'Standard Lengths', value: '1mtr, 2mtr, cut to length' },
      { label: 'Colour', value: 'Brown (Bakelite), Natural/Green (Epoxy)' },
      { label: 'Custom Sizes', value: 'Available on request' },
    ],
    descriptionPoints: [
      { icon: '⚡', heading: 'High Electrical Insulation', text: 'Insulation rods provide high dielectric strength and volume resistivity — used as structural insulating supports in switchgear, transformers, and electrical panels.' },
      { icon: '💪', heading: 'Mechanical Strength', text: 'Suitable for use as structural supports and spacers in electrical equipment where both mechanical load-bearing and electrical isolation are required.' },
      { icon: '🔧', heading: 'Machinable to Drawing', text: 'Easily machined into custom insulators, bushes, standoffs, and spacers on standard CNC equipment. Supplied in rod form for in-house machining.' },
      { icon: '🌡️', heading: 'Thermal Stability', text: 'Maintains electrical properties over a wide temperature range. Epoxy grades offer higher temperature performance than standard bakelite.' },
    ],
    applications: ['Switchgear Insulators', 'Transformer Supports', 'Busbar Spacers', 'Electrical Panel Standoffs', 'HV Equipment Insulators', 'Motor Insulation Components'],
    faqs: [
      { q: 'What grades of insulation rod do you supply?', a: 'We supply Bakelite (phenol-formaldehyde), Epoxy glass (FR4/G10), and phenolic grades. Contact us with your voltage, temperature, and mechanical requirements for grade selection.' },
      { q: 'What diameter range is available for insulation rods?', a: 'Standard insulation rods from 6mm to 200mm diameter in standard lengths of 1mtr and 2mtr. Cut-to-length and custom diameters available on request.' },
      { q: 'Can insulation rods be machined into custom components?', a: 'Yes. All insulation rod grades machine well on standard CNC equipment into custom insulators, standoffs, bushes, and spacers.' },
    ],
  },

  // ─── CUSTOM EP COMPONENTS ────────────────────────────────────────────────────
  'ep-custom-components': {
    title: 'Custom Engineering Plastic Components',
    subtitle: 'As-Per-Drawing Machined Parts',
    category: 'Custom Components',
    sku: 'VG-EP-CUST',
    mpn: 'VG-EP-CUST',
    image: '/placeholder-ep-custom.jpg',
    imageAlt: 'Custom Engineering Plastic Components - Visanix Global',
    heroDescription: 'Precision-machined engineering plastic components manufactured to your exact drawings from any material in our range. From single prototype parts to production batches.',
    metaTitle: 'Custom Engineering Plastic Components India | Machined to Drawing | Visanix Global',
    metaDescription: 'Custom engineering plastic components machined to your drawings by Visanix Global, Delhi NCR. All materials — PEEK, POM, Nylon, PU, PP, PVC, Silicone, Epoxy, ABS.',
    specs: [
      { label: 'Materials Available', value: 'PEEK, POM/Delrin, Cast Nylon, PU, PP, PVC, Silicone, Epoxy FR4, ABS, Acrylic' },
      { label: 'Supply Basis', value: 'As per drawing / DXF / CAD model' },
      { label: 'Quantity', value: 'Prototype (1 off) to production batch' },
      { label: 'Lead Time', value: '5–15 working days (material/complexity dependent)' },
      { label: 'Size Reference', value: 'As per drawing' },
    ],
    descriptionPoints: [
      { icon: '📐', heading: 'Any Engineering Plastic', text: 'Components machined from any material in our range — from PEEK for demanding applications to ABS and PP for general engineering requirements.' },
      { icon: '🔧', heading: 'To Your Exact Drawing', text: 'Supply DXF, STEP, IGES or PDF drawing and we manufacture to your exact dimensions and tolerances.' },
      { icon: '📦', heading: 'Prototype to Production', text: 'Single prototype parts through to production batches with consistent quality and full dimensional traceability.' },
      { icon: '💬', heading: 'Material Selection Support', text: 'Not sure which material suits your application? Tell us the operating conditions and we will recommend the right material and grade.' },
    ],
    applications: ['Precision Bushes & Bearings', 'Wear Components', 'Valve Bodies & Seats', 'Gears & Cams', 'Structural Brackets', 'Chemical Plant Parts', 'Electrical Insulators', 'Food Machinery Components'],
    faqs: [
      { q: 'What materials can you machine custom components from?', a: 'We machine from the full range including PEEK, POM/Delrin, cast nylon (PA6), polyurethane, polypropylene, PVC, silicone, epoxy FR4/G10, acrylic, and ABS.' },
      { q: 'What is the minimum order quantity?', a: 'We supply from single prototype parts (1 off) to production batches. There is no minimum order quantity.' },
      { q: 'What drawing formats do you accept?', a: 'We accept DXF, STEP, IGES, and PDF drawings.' },
    ],
  },

};
