export const productData = {
    'ptfe-rod': {
        title: 'PTFE Rod',
        teflonName: 'Teflon Rod',
        teflonNote: 'PTFE rods are also commonly referred to as Teflon rods. Teflon is a brand name for PTFE (polytetrafluoroethylene) originally developed by DuPont. Whether you search for a Teflon rod or a PTFE rod, Visanix Global supplies both virgin and filled grades from Gurugram across India.',
        subtitle: 'Extruded and Moulded',
        sku: 'VG-PTFE-ROD',
        mpn: 'VG-PTFE-ROD',
        image: '/ptfe-rod-hd.jpg',
        imageAlt: 'PTFE Rod supplier India - Visanix Global',
        heroDescription: 'High-purity PTFE rods available in extruded and moulded grades. Supplied in standard diameters from 6mm to 200mm for machining into bushes, bearings, seals, and custom components.',
        metaTitle: 'PTFE Rod Supplier India | Extruded & Moulded | Visanix Global',
        metaDescription: 'Buy PTFE rods in 6mm–200mm diameter from Visanix Global, Gurugram. Extruded and moulded grades. Virgin, glass-filled, carbon-filled. Custom lengths available.',
        specs: [
            { label: 'Diameter Range', value: '6mm – 200mm' },
            { label: 'Standard Lengths', value: '1 mtr, 1 ft, 905mm' },
            { label: 'Grades Available', value: 'Virgin, Glass Filled, Carbon Filled' },
            { label: 'Manufacturing Method', value: 'Extruded & Moulded' },
            { label: 'Colour', value: 'White (Virgin), Black (Filled)' },
        ],
        descriptionPoints: [
            { icon: '🧪', heading: 'Chemical Resistance', text: 'Virgin PTFE rods offer near-universal chemical resistance, making them ideal for use in aggressive acid, alkali, and solvent environments.' },
            { icon: '⚙️', heading: 'Machinability', text: 'Easily machined into bushes, bearings, valve seats, and custom components. Tight tolerances achievable with standard CNC equipment.' },
            { icon: '🌡️', heading: 'Temperature Range', text: 'Continuous service from -200°C to +260°C. Retains mechanical properties across extreme thermal cycles.' },
            { icon: '📐', heading: 'Custom Sizes', text: 'Non-standard diameters and lengths available on request. Filled grades (glass, carbon, graphite) for enhanced wear and load performance.' },
        ],
        applications: ['Valve Seats', 'Bushes & Bearings', 'Piston Rings', 'Slide Plates', 'Chemical Processing', 'Pharmaceutical Equipment', 'Food Industry'],
        faqs: [
            { q: 'What diameter range do you supply for PTFE rods?', a: 'We supply PTFE rods from 6mm to 200mm diameter in both extruded and moulded grades.' },
            { q: 'What grades of PTFE rod are available?', a: 'We supply Virgin PTFE rods as well as filled grades including 25% Glass Filled, 25% Carbon Filled and 25% Graphite Filled.' },
            { q: 'What industries use PTFE rods?', a: 'PTFE rods are widely used in chemical processing, pharmaceutical manufacturing, oil and gas, food processing and general industrial manufacturing for machining into bushes, bearings, rings and other components.' },
            { q: 'Can you supply PTFE rods in custom lengths?', a: 'Standard lengths are 1 metre, 1 foot and 905mm. Custom lengths available on request.' },
            { q: 'Do you provide MTC with PTFE rods?', a: 'Yes. Material Test Certificates provided with every order.' },
        ],
    },

    'ptfe-sheet-skived': {
        title: 'PTFE Skived Sheet',
        teflonName: 'Teflon Skived Sheet',
        teflonNote: 'PTFE skived sheets are also known as Teflon sheets. Teflon is the widely recognised brand name for PTFE. Whether you are searching for a Teflon sheet or a PTFE skived sheet, Visanix Global supplies precision skived grades in widths up to 2 metres across India.',
        subtitle: 'Thin Film to 6mm',
        sku: 'VG-PTFE-SKV',
        mpn: 'VG-PTFE-SKV',
        image: '/ptfe-skived-sheet.webp',
        imageAlt: 'PTFE Skived Sheet supplier India - Visanix Global',
        heroDescription: 'Precision skived PTFE sheets offering excellent surface finish and consistent thickness. Available in widths up to 2 metres for gaskets, linings, and electrical insulation.',
        metaTitle: 'PTFE Skived Sheet Supplier India | Visanix Global Gurugram',
        metaDescription: 'Buy PTFE skived sheets 0.5mm–6mm thick, widths up to 2mtr. Supplied by Visanix Global, Gurugram. Ideal for gaskets, linings, and insulation. Custom cutting available.',
        specs: [
            { label: 'Thickness Range', value: '0.5mm – 6mm' },
            { label: 'Available Widths', value: '1mtr, 1.2mtr, 1.5mtr, 2mtr' },
            { label: 'Surface Finish', value: 'Smooth (skived process)' },
            { label: 'Grade', value: 'Virgin PTFE' },
            { label: 'Custom Cutting', value: 'Available to drawing' },
        ],
        descriptionPoints: [
            { icon: '✂️', heading: 'Skived Process', text: 'Produced by shaving thin layers from a moulded billet, resulting in a smooth, consistent surface ideal for sealing and lining applications.' },
            { icon: '🔌', heading: 'Electrical Insulation', text: 'Excellent dielectric properties make skived PTFE sheet a preferred choice for electrical insulation in high-frequency and high-voltage applications.' },
            { icon: '🛡️', heading: 'Chemical Lining', text: 'Used to line tanks, pipes, and vessels handling aggressive chemicals. Provides a non-stick, corrosion-resistant barrier.' },
            { icon: '📏', heading: 'Precision Thickness', text: 'Tight thickness tolerances maintained throughout the roll. Suitable for die-cutting gaskets and seals to exact dimensions.' },
        ],
        applications: ['Gaskets', 'Tank Linings', 'Pipe Linings', 'Electrical Insulation', 'Slide Bearings', 'Chemical Processing', 'Food Equipment'],
        faqs: [
            { q: 'What thickness range do you supply for skived PTFE sheets?', a: 'We supply skived PTFE sheets from 0.5mm to 6mm thickness.' },
            { q: 'What widths are available for skived sheets?', a: 'Standard widths are 1 metre, 1.2 metre, 1.5 metre and 2 metre.' },
            { q: 'What is the difference between skived and moulded PTFE sheet?', a: 'Skived sheets are cut from a moulded billet giving excellent surface finish and tight dimensional tolerance — ideal for gaskets, liners and thin sheet applications. Moulded sheets are compression moulded and available in thicker sections from 5mm to 100mm for structural and heavy-duty applications.' },
            { q: 'Can skived PTFE sheets be custom cut?', a: 'Yes. We offer custom cutting to your dimensions or DXF drawings.' },
            { q: 'Do you provide MTC with skived PTFE sheets?', a: 'Yes. Material Test Certificates provided with every order.' },
        ],
    },

    'ptfe-sheet-moulded': {
        title: 'PTFE Moulded Sheet',
        teflonName: 'Teflon Moulded Sheet',
        teflonNote: 'PTFE moulded sheets are also referred to as Teflon sheets or Teflon plates. Teflon is the popular brand name for PTFE. Visanix Global supplies compression-moulded PTFE sheets in thicknesses from 5mm to 100mm to customers across India.',
        subtitle: 'Heavy Thickness 5mm–100mm',
        sku: 'VG-PTFE-MLD',
        mpn: 'VG-PTFE-MLD',
        image: '/ptfe-sheets-moulded.jpg',
        imageAlt: 'PTFE Moulded Sheet supplier India - Visanix Global',
        heroDescription: 'Compression-moulded PTFE sheets for heavy-duty structural and sealing applications. Available in thicknesses from 5mm to 100mm and standard slab sizes.',
        metaTitle: 'PTFE Moulded Sheet Supplier India | 5mm–100mm | Visanix Global',
        metaDescription: 'Buy PTFE moulded sheets 5mm–100mm thick from Visanix Global, Gurugram. Standard sizes 1x1m, 2x2m. Virgin and filled grades. Custom machining available.',
        specs: [
            { label: 'Thickness Range', value: '5mm – 100mm' },
            { label: 'Standard Sizes', value: '1×1m, 2×2m, 0.6×0.6m' },
            { label: 'Grades Available', value: 'Virgin, Glass Filled, Carbon Filled' },
            { label: 'Manufacturing Method', value: 'Compression Moulded' },
            { label: 'Custom Machining', value: 'Available' },
        ],
        descriptionPoints: [
            { icon: '🏗️', heading: 'Structural Applications', text: 'Thick moulded sheets are used for bridge bearings, expansion joints, and structural slide plates where high compressive loads are involved.' },
            { icon: '🔧', heading: 'Machinable Blanks', text: 'Supplied as blanks for CNC machining into custom components. Filled grades offer improved dimensional stability under load.' },
            { icon: '🌡️', heading: 'Thermal Stability', text: 'Maintains properties from cryogenic temperatures to +260°C. Suitable for heat exchanger components and furnace applications.' },
            { icon: '📦', heading: 'Large Format Available', text: '2×2m slabs available for large-scale lining and structural projects. Cut-to-size service available.' },
        ],
        applications: ['Bridge Bearings', 'Expansion Joints', 'Structural Slide Plates', 'Machined Components', 'Heat Exchanger Parts', 'Chemical Vessels'],
        faqs: [
            { q: 'What thickness range do you supply for moulded PTFE sheets?', a: 'We supply moulded PTFE sheets from 5mm to 100mm thickness.' },
            { q: 'What standard sizes are available?', a: 'Standard slab sizes are 1×1m, 2×2m and 0.6×0.6m. Custom sizes available on request.' },
            { q: 'What grades of moulded PTFE sheet are available?', a: 'We supply Virgin PTFE as well as 15% Glass Filled, 25% Glass Filled, 25% Carbon Filled and 25% Graphite Filled moulded sheets.' },
            { q: 'Can moulded PTFE sheets be machined?', a: 'Yes. Moulded sheets are ideal machinable blanks for CNC machining into custom components, slide plates and structural parts.' },
            { q: 'Do you provide MTC with moulded PTFE sheets?', a: 'Yes. Material Test Certificates provided with every order.' },
        ],
    },

    'ptfe-tube': {
        title: 'PTFE Tubes',
        teflonName: 'Teflon Tube',
        teflonNote: 'PTFE tubes are also commonly called Teflon tubes or Teflon tubing. Teflon is the well-known brand name for PTFE. Visanix Global supplies extruded and moulded PTFE tubes across a full OD/ID range to customers across India.',
        subtitle: 'Extruded and Moulded',
        sku: 'VG-PTFE-TUB',
        mpn: 'VG-PTFE-TUB',
        image: '/ptfe-tubes.jfif',
        imageAlt: 'PTFE Tube supplier India - Visanix Global',
        heroDescription: 'PTFE tubes in extruded and moulded grades for fluid handling, electrical insulation, and chemical transfer. Available in coils or straight lengths across a full OD/ID range.',
        metaTitle: 'PTFE Tube Supplier India | Extruded & Moulded | Visanix Global',
        metaDescription: 'Buy PTFE tubes in full OD/ID range from Visanix Global, Gurugram. Extruded and moulded grades. Supplied in coils or straight lengths. Custom sizes available.',
        specs: [
            { label: 'OD/ID Specs', value: 'Full Range Available' },
            { label: 'Delivery Form', value: 'Coils or Straight Lengths' },
            { label: 'Grades Available', value: 'Virgin, Filled Grades' },
            { label: 'Manufacturing Method', value: 'Extruded & Moulded' },
            { label: 'Custom Sizes', value: 'Available on Request' },
        ],
        descriptionPoints: [
            { icon: '💧', heading: 'Fluid Handling', text: 'Inert to virtually all chemicals. Used in laboratory, pharmaceutical, and chemical plant fluid transfer lines where contamination must be avoided.' },
            { icon: '🔌', heading: 'Electrical Insulation', text: 'Extruded PTFE tubing provides excellent dielectric insulation for wire and cable harnesses in aerospace and electronics.' },
            { icon: '🌡️', heading: 'High Temperature', text: 'Continuous service to +260°C. Suitable for heat shrink applications and high-temperature fluid lines.' },
            { icon: '📐', heading: 'Custom OD/ID', text: 'Non-standard bore and wall thickness combinations available. Moulded tubes for larger diameters and thicker walls.' },
        ],
        applications: ['Chemical Transfer Lines', 'Laboratory Tubing', 'Wire Insulation', 'Pharmaceutical Fluid Lines', 'Heat Exchanger Tubes', 'Pneumatic Systems'],
        faqs: [
            { q: 'What OD and ID range do you supply for PTFE tubes?', a: 'We supply PTFE tubes across a full OD/ID range in both extruded and moulded grades. Contact us with your specific OD, ID and wall thickness requirement.' },
            { q: 'Are PTFE tubes available in coils or straight lengths?', a: 'Yes. Extruded PTFE tubes are available in coils or straight lengths depending on diameter. Moulded tubes are supplied in straight lengths.' },
            { q: 'What grades of PTFE tube are available?', a: 'We supply Virgin PTFE tubes as well as filled grades for specific mechanical or electrical requirements.' },
            { q: 'Are PTFE tubes suitable for pharmaceutical fluid transfer?', a: 'Yes. Virgin PTFE tubes are chemically inert, non-toxic and suitable for pharmaceutical fluid transfer applications.' },
            { q: 'Do you provide MTC with PTFE tubes?', a: 'Yes. Material Test Certificates provided with every order.' },
        ],
    },

    'ptfe-bush': {
        title: 'PTFE Bush',
        teflonName: 'Teflon Bush',
        teflonNote: 'PTFE bushes are also known as Teflon bushes or Teflon bearings. Teflon is the popular brand name for PTFE. Visanix Global manufactures custom PTFE bushes to your OD/ID specifications in virgin and filled grades for customers across India.',
        subtitle: 'Custom Manufactured',
        sku: 'VG-PTFE-BSH',
        mpn: 'VG-PTFE-BSH',
        image: '/ptfe bush.jfif',
        imageAlt: 'PTFE Bush supplier India - Visanix Global',
        heroDescription: 'Precision-machined PTFE bushes for bearing and sliding applications. Manufactured to your OD/ID specifications in virgin and filled grades up to 500mm length.',
        metaTitle: 'PTFE Bush Manufacturer India | Custom Sizes | Visanix Global',
        metaDescription: 'Custom PTFE bushes manufactured to your drawings by Visanix Global, Gurugram. Virgin and filled grades. OD/ID to specification, up to 500mm length.',
        specs: [
            { label: 'OD/ID Ranges', value: 'Custom Manufactured' },
            { label: 'Max Length', value: 'Up to 500mm' },
            { label: 'Grades Available', value: 'Virgin, Glass Filled, Carbon Filled' },
            { label: 'Tolerances', value: 'As per drawing' },
            { label: 'Lead Time', value: '3–7 working days' },
        ],
        descriptionPoints: [
            { icon: '⚙️', heading: 'Self-Lubricating', text: 'PTFE bushes require no external lubrication, reducing maintenance costs in pumps, valves, and rotating equipment.' },
            { icon: '🔩', heading: 'Wear Resistance', text: 'Carbon and glass-filled grades offer significantly improved wear life compared to virgin PTFE in dynamic applications.' },
            { icon: '🧪', heading: 'Chemical Compatibility', text: 'Suitable for use in aggressive chemical environments where metal or plastic bushes would corrode or degrade.' },
            { icon: '📐', heading: 'Precision Machining', text: 'Machined to tight tolerances from rod or tube stock. Flanged, split, and custom profile bushes available.' },
        ],
        applications: ['Pumps', 'Valves', 'Hydraulic Cylinders', 'Chemical Equipment', 'Food Processing Machinery', 'Pharmaceutical Equipment'],
        faqs: [
            { q: 'Can you supply PTFE bushes to custom OD and ID dimensions?', a: 'Yes. All PTFE bushes are custom manufactured to your OD, ID and length specifications as per your engineering drawings.' },
            { q: 'What grades of PTFE bush are available?', a: 'We supply Virgin PTFE, 25% Glass Filled, 25% Carbon Filled and 25% Graphite Filled bushes depending on your load, wear and chemical resistance requirements.' },
            { q: 'Do PTFE bushes require lubrication?', a: 'No. PTFE bushes are self-lubricating and require no external lubrication, reducing maintenance costs in pumps, valves and rotating equipment.' },
            { q: 'What is the lead time for custom PTFE bushes?', a: 'Typical lead time is 3–7 working days depending on dimensions and quantity. Contact us for a specific timeline.' },
            { q: 'Do you provide MTC with PTFE bushes?', a: 'Yes. Material Test Certificates provided with every order.' },
        ],
    },

    'ptfe-ball': {
        title: 'PTFE Ball',
        teflonName: 'Teflon Ball',
        teflonNote: 'PTFE balls are also referred to as Teflon balls. Teflon is the widely recognised brand name for PTFE. Visanix Global supplies precision PTFE balls from 3mm to 50mm diameter for ball valves and flow control applications across India.',
        subtitle: '3mm – 50mm Diameter',
        sku: 'VG-PTFE-BLL',
        mpn: 'VG-PTFE-BLL',
        image: '/ptfe ball.jfif',
        imageAlt: 'PTFE Ball supplier India - Visanix Global',
        heroDescription: 'Precision PTFE balls for ball valves, check valves, and flow control applications. Available from 3mm to 50mm in standard industrial grade.',
        metaTitle: 'PTFE Ball Supplier India | 3mm–50mm | Visanix Global',
        metaDescription: 'Buy PTFE balls 3mm–50mm from Visanix Global, Gurugram. Standard industrial grade. Used in ball valves, check valves, and flow control. Bulk supply available.',
        specs: [
            { label: 'Size Range', value: '3mm – 50mm diameter' },
            { label: 'Precision Grade', value: 'Standard Industrial' },
            { label: 'Material', value: 'Virgin PTFE' },
            { label: 'Surface Finish', value: 'Smooth, precision ground' },
            { label: 'Custom Sizes', value: 'Available on Request' },
        ],
        descriptionPoints: [
            { icon: '🔵', heading: 'Ball Valve Applications', text: 'PTFE balls are used as the seating element in ball valves handling corrosive fluids, acids, and high-purity media.' },
            { icon: '🧪', heading: 'Chemical Inertness', text: 'Virgin PTFE is resistant to virtually all industrial chemicals, making these balls suitable for the most aggressive process environments.' },
            { icon: '🌡️', heading: 'Temperature Range', text: 'Operates reliably from cryogenic temperatures to +260°C, covering the full range of industrial process conditions.' },
            { icon: '📦', heading: 'Bulk Supply', text: 'Available in bulk quantities for valve manufacturers and OEMs. Consistent dimensional accuracy across batches.' },
        ],
        applications: ['Ball Valves', 'Check Valves', 'Flow Control', 'Chemical Processing', 'Pharmaceutical Valves', 'Food & Beverage'],
        faqs: [
            { q: 'What size range do you supply for PTFE balls?', a: 'We supply PTFE balls from 3mm to 50mm diameter in standard industrial grade. Custom sizes available on request.' },
            { q: 'What grade of PTFE is used for balls?', a: 'Standard PTFE balls are manufactured from Virgin PTFE for maximum chemical resistance and purity.' },
            { q: 'Are PTFE balls suitable for chemical valve applications?', a: 'Yes. Virgin PTFE balls are resistant to virtually all industrial chemicals and are widely used in ball valves handling corrosive fluids and high-purity media.' },
            { q: 'Can you supply PTFE balls in bulk quantities?', a: 'Yes. We supply PTFE balls in bulk quantities for valve manufacturers and OEMs with consistent dimensional accuracy across batches.' },
            { q: 'Do you provide MTC with PTFE balls?', a: 'Yes. Material Test Certificates provided with every order.' },
        ],
    },

    'ptfe-gland': {
        title: 'PTFE Gland Packing',
        teflonName: 'Teflon Gland Packing',
        teflonNote: 'PTFE gland packing is also known as Teflon gland packing or Teflon packing rope. Teflon is the popular brand name for PTFE. Visanix Global supplies PTFE gland packing in square sections from 3×3mm to 12×12mm to pump and valve users across India.',
        subtitle: 'Braided & Moulded',
        sku: 'VG-PTFE-GLD',
        mpn: 'VG-PTFE-GLD',
        image: '/ptfe gland.jfif',
        imageAlt: 'PTFE Gland Packing supplier India - Visanix Global',
        heroDescription: 'PTFE gland packing in standard square sections from 3×3mm to 12×12mm. Supplied on spools of 1kg, 5kg, and 10kg for pump and valve stem sealing.',
        metaTitle: 'PTFE Gland Packing Supplier India | Visanix Global Gurugram',
        metaDescription: 'Buy PTFE gland packing 3×3mm to 12×12mm from Visanix Global, Gurugram. Spools of 1kg, 5kg, 10kg. For pump and valve stem sealing. Bulk supply available.',
        specs: [
            { label: 'Standard Sections', value: '3×3mm up to 12×12mm' },
            { label: 'Packaging', value: 'Spools of 1kg, 5kg, 10kg' },
            { label: 'Material', value: 'Expanded PTFE / Braided PTFE' },
            { label: 'Temperature Range', value: '-200°C to +260°C' },
            { label: 'Custom Sections', value: 'Available on Request' },
        ],
        descriptionPoints: [
            { icon: '🔧', heading: 'Pump Sealing', text: 'Used to seal pump shafts and valve stems in chemical, water treatment, and process industries. Easy to install and replace.' },
            { icon: '🧪', heading: 'Universal Chemical Resistance', text: 'PTFE gland packing is compatible with virtually all process fluids including strong acids, alkalis, and solvents.' },
            { icon: '💧', heading: 'Low Friction', text: 'Inherently low coefficient of friction reduces shaft wear and operating torque compared to conventional packing materials.' },
            { icon: '📦', heading: 'Spool Supply', text: 'Supplied on convenient spools for easy dispensing. Bulk coils available for high-volume users and distributors.' },
        ],
        applications: ['Pump Shaft Sealing', 'Valve Stem Packing', 'Agitator Seals', 'Chemical Pumps', 'Water Treatment', 'Food Processing'],
        faqs: [
            { q: 'What section sizes do you supply for PTFE gland packing?', a: 'We supply PTFE gland packing in standard square sections from 3×3mm up to 12×12mm. Custom sections available on request.' },
            { q: 'What packaging options are available for gland packing?', a: 'PTFE gland packing is supplied on spools of 1kg, 5kg and 10kg. Bulk coils available for high-volume users.' },
            { q: 'Is PTFE gland packing suitable for chemical pump sealing?', a: 'Yes. PTFE gland packing is compatible with virtually all process fluids including strong acids, alkalis and solvents, making it ideal for chemical pump and valve sealing.' },
            { q: 'What temperature range does PTFE gland packing handle?', a: 'PTFE gland packing operates from -200°C to +260°C continuous service temperature.' },
            { q: 'Do you provide MTC with PTFE gland packing?', a: 'Yes. Material Test Certificates provided with every order.' },
        ],
    },

    'ptfe-gasket': {
        title: 'PTFE Gasket',
        teflonName: 'Teflon Gasket',
        teflonNote: 'PTFE gaskets are also commonly called Teflon gaskets. Teflon is the well-known brand name for PTFE. Visanix Global supplies custom-cut PTFE gaskets to your flange drawings for chemical, pharmaceutical, and food processing pipelines across India.',
        subtitle: 'Custom Cut to Drawing',
        sku: 'VG-PTFE-GSK',
        mpn: 'VG-PTFE-GSK',
        image: '/ptfe gasket.jfif',
        imageAlt: 'PTFE Gasket supplier India - Visanix Global',
        heroDescription: 'Custom-cut PTFE gaskets for flanged joints in chemical, pharmaceutical, and food processing pipelines. Cut to your drawings from 1mm to 5mm sheet.',
        metaTitle: 'PTFE Gasket Manufacturer India | Custom Cut | Visanix Global',
        metaDescription: 'Custom PTFE gaskets cut to your drawings by Visanix Global, Gurugram. 1mm–5mm thickness. For chemical, pharma, and food pipelines. Fast turnaround.',
        specs: [
            { label: 'Custom Cutting', value: 'As per drawings / DXF files' },
            { label: 'Thickness', value: '1mm – 5mm' },
            { label: 'Material', value: 'Virgin PTFE / Expanded PTFE' },
            { label: 'Standards', value: 'ASME, DIN, BS flange standards' },
            { label: 'Lead Time', value: '2–5 working days' },
        ],
        descriptionPoints: [
            { icon: '🔩', heading: 'Flange Sealing', text: 'PTFE gaskets provide a reliable, chemically inert seal for flanged pipe joints in aggressive process environments.' },
            { icon: '🧪', heading: 'FDA Compliant', text: 'Virgin PTFE gaskets are FDA compliant and suitable for food, beverage, and pharmaceutical applications.' },
            { icon: '✂️', heading: 'Cut to Drawing', text: 'Supply your DXF file or flange standard and we cut to exact dimensions. Standard flange sizes held in stock.' },
            { icon: '📐', heading: 'Expanded PTFE Option', text: 'ePTFE gaskets available for low bolt-load applications and irregular flange surfaces. Excellent conformability.' },
        ],
        applications: ['Chemical Pipelines', 'Pharmaceutical Pipelines', 'Food Processing', 'Water Treatment', 'Oil & Gas', 'Flanged Joints'],
        faqs: [
            { q: 'Can you supply PTFE gaskets cut to custom dimensions?', a: 'Yes. We cut PTFE gaskets to your exact dimensions from DXF files, engineering drawings or standard flange specifications (ASME, DIN, BS).' },
            { q: 'What thickness range is available for PTFE gaskets?', a: 'We supply PTFE gaskets from 1mm to 5mm thickness. Thicker sections available on request.' },
            { q: 'Are your PTFE gaskets suitable for pharmaceutical pipelines?', a: 'Yes. Virgin PTFE gaskets are FDA compliant and suitable for direct contact with pharmaceutical ingredients and process fluids.' },
            { q: 'What is the lead time for custom PTFE gaskets?', a: 'Typical lead time is 2–5 working days for custom cut gaskets. Standard flange sizes are held in stock for faster delivery.' },
            { q: 'Do you provide MTC with PTFE gaskets?', a: 'Yes. Material Test Certificates provided with every order.' },
        ],
    },

    'ptfe-ring': {
        title: 'PTFE Ring',
        teflonName: 'Teflon Ring',
        teflonNote: 'PTFE rings are also known as Teflon rings or Teflon seals. Teflon is the popular brand name for PTFE. Visanix Global supplies PTFE back-up rings, O-rings and V-rings in standard and custom sizes for hydraulic and chemical sealing applications across India.',
        subtitle: 'Back-up, O-Rings & V-Rings',
        sku: 'VG-PTFE-RNG',
        mpn: 'VG-PTFE-RNG',
        image: '/ptfe ring.jfif',
        imageAlt: 'PTFE Ring supplier India - Visanix Global',
        heroDescription: 'PTFE rings including back-up rings, O-rings, and V-rings in standard and custom sizes. Used in hydraulic, pneumatic, and chemical sealing applications.',
        metaTitle: 'PTFE Ring Supplier India | Back-up, O-Ring, V-Ring | Visanix Global',
        metaDescription: 'Buy PTFE back-up rings, O-rings, and V-rings from Visanix Global, Gurugram. Standard and custom sizes. For hydraulic, pneumatic, and chemical sealing.',
        specs: [
            { label: 'Types', value: 'Back-up Rings, O-Rings, V-Rings' },
            { label: 'Sizing', value: 'Standard & Custom' },
            { label: 'Material', value: 'Virgin PTFE / Filled PTFE' },
            { label: 'Standards', value: 'AS568, Metric, Custom' },
            { label: 'Lead Time', value: '3–7 working days' },
        ],
        descriptionPoints: [
            { icon: '🔵', heading: 'Back-up Rings', text: 'PTFE back-up rings prevent extrusion of elastomeric O-rings under high pressure in hydraulic and pneumatic cylinders.' },
            { icon: '⚙️', heading: 'V-Ring Seals', text: 'PTFE V-rings provide effective sealing in rotary and reciprocating applications with minimal friction and long service life.' },
            { icon: '🧪', heading: 'Chemical Sealing', text: 'Where elastomeric O-rings are incompatible with process fluids, PTFE O-rings provide a chemically inert alternative.' },
            { icon: '📐', heading: 'Custom Profiles', text: 'Non-standard ring profiles machined or moulded to your drawings. Filled grades for improved wear in dynamic applications.' },
        ],
        applications: ['Hydraulic Cylinders', 'Pneumatic Cylinders', 'Chemical Valves', 'Pump Seals', 'Rotary Seals', 'High-Pressure Systems'],
        faqs: [
            { q: 'What types of PTFE rings do you supply?', a: 'We supply PTFE back-up rings, O-rings and V-rings in standard AS568, metric and custom sizes.' },
            { q: 'What is the purpose of a PTFE back-up ring?', a: 'PTFE back-up rings prevent extrusion of elastomeric O-rings under high pressure in hydraulic and pneumatic cylinders, extending seal life significantly.' },
            { q: 'Can you supply custom PTFE ring profiles?', a: 'Yes. Non-standard ring profiles are machined or moulded to your drawings. Filled grades available for improved wear in dynamic applications.' },
            { q: 'What PTFE grades are available for rings?', a: 'We supply Virgin PTFE and filled grades (glass, carbon, graphite) depending on your pressure, wear and chemical resistance requirements.' },
            { q: 'Do you provide MTC with PTFE rings?', a: 'Yes. Material Test Certificates provided with every order.' },
        ],
    },

    'ptfe-tape': {
        title: 'PTFE Tape',
        teflonName: 'Teflon Tape',
        teflonNote: 'PTFE thread seal tape is also universally known as Teflon tape. Teflon is the brand name for PTFE. Whether you search for Teflon tape or PTFE tape, Visanix Global supplies thread seal tape in 12mm and 19mm widths in bulk quantities across India.',
        subtitle: 'Thread Seal Tape',
        sku: 'VG-PTFE-TPE',
        mpn: 'VG-PTFE-TPE',
        image: '/ptfe tape.jfif',
        imageAlt: 'PTFE Thread Seal Tape supplier India - Visanix Global',
        heroDescription: 'PTFE thread seal tape in standard widths of 12mm and 19mm. Supplied in rolls of 7m, 10m, and 12m for pipe thread sealing in plumbing, gas, and chemical applications.',
        metaTitle: 'PTFE Thread Seal Tape Supplier India | Visanix Global',
        metaDescription: 'Buy PTFE thread seal tape 12mm and 19mm wide from Visanix Global, Gurugram. Rolls of 7m, 10m, 12m. For plumbing, gas, and chemical pipe threads. Bulk supply.',
        specs: [
            { label: 'Standard Widths', value: '12mm, 19mm' },
            { label: 'Roll Length', value: '7mtr, 10mtr, 12mtr' },
            { label: 'Thickness', value: '0.075mm – 0.1mm' },
            { label: 'Material', value: 'Expanded PTFE' },
            { label: 'Bulk Supply', value: 'Available' },
        ],
        descriptionPoints: [
            { icon: '🔧', heading: 'Thread Sealing', text: 'Wraps around male pipe threads to create a leak-free seal on NPT, BSP, and metric threaded connections.' },
            { icon: '🧪', heading: 'Chemical Resistance', text: 'Compatible with water, gas, steam, acids, and most industrial fluids. Safe for potable water systems.' },
            { icon: '📦', heading: 'Bulk Supply', text: 'Available in bulk rolls and carton quantities for plumbing contractors, distributors, and industrial users.' },
            { icon: '✅', heading: 'Easy Application', text: 'Soft, conformable tape that is easy to apply by hand. No special tools required. Repositionable before tightening.' },
        ],
        applications: ['Plumbing', 'Gas Lines', 'Chemical Pipelines', 'Steam Lines', 'Hydraulic Fittings', 'Industrial Maintenance'],
        faqs: [
            { q: 'What widths and lengths do you supply for PTFE tape?', a: 'We supply PTFE thread seal tape in 12mm and 19mm widths in roll lengths of 7 metres, 10 metres and 12 metres.' },
            { q: 'Is PTFE tape suitable for gas line applications?', a: 'Yes. PTFE thread seal tape is suitable for gas, water, steam and chemical pipe thread sealing applications.' },
            { q: 'Can you supply PTFE tape in bulk quantities?', a: 'Yes. We supply PTFE tape in bulk rolls and carton quantities for plumbing contractors, distributors and industrial users.' },
            { q: 'What thread standards is PTFE tape compatible with?', a: 'PTFE tape is compatible with NPT, BSP and metric threaded connections.' },
            { q: 'Do you provide MTC with PTFE tape?', a: 'Yes. Material Test Certificates provided with every order.' },
        ],
    },
};
