export const industryData = {
    'pharmaceutical': {
        metaTitle: 'PTFE Solutions for Pharmaceutical Industry | Visanix Global',
        metaDescription: 'Visanix Global supplies FDA-compliant, USP Class VI PTFE products for pharmaceutical manufacturing. PTFE gaskets, tubes, rods and sheets for cGMP environments.',
        h1: 'PTFE & Engineering Materials for Pharmaceutical Manufacturing',
        tag: 'Pharmaceutical Industry',
        heroDescription: 'Chemically inert, FDA-compliant PTFE materials for clean-room pharmaceutical manufacturing environments.',
        whyPTFE: 'PTFE is the material of choice in pharmaceutical manufacturing because it is chemically inert, non-toxic, and non-contaminating. As a leading <strong>PTFE supplier for the pharmaceutical industry in India</strong>, Visanix Global supplies <strong>FDA grade PTFE</strong> and <strong>USP Class VI PTFE</strong> products suitable for direct contact with active pharmaceutical ingredients (APIs), solvents, and process fluids. PTFE does not leach, absorb, or react with any pharmaceutical compound, ensuring zero contamination risk throughout the production process. Its smooth, non-stick surface is easy to clean and sterilise, making it ideal for cGMP-compliant manufacturing environments. PTFE components can be autoclaved and are compatible with all standard pharmaceutical cleaning agents and sterilisation protocols. Whether you need a Teflon gasket for a pharmaceutical pipeline or a PTFE tube for fluid transfer, Visanix Global supplies the right grade with full material traceability.',
        compliance: ['FDA 21 CFR', 'USP Class VI', 'cGMP Compatible', 'Autoclavable'],
        keyBenefit: 'Zero contamination risk — chemically inert, FDA compliant, autoclavable',
        recommendedProducts: [
            { name: 'PTFE Gasket', href: '/products/ptfe-gasket', use: 'Flange sealing in API and solvent pipelines' },
            { name: 'PTFE Tube', href: '/products/ptfe-tube', use: 'Fluid transfer lines for pharmaceutical media' },
            { name: 'PTFE Rod', href: '/products/ptfe-rod', use: 'Machined into valve seats and custom components' },
            { name: 'PTFE Skived Sheet', href: '/products/ptfe-sheet-skived', use: 'Lining for reactors and storage vessels' },
        ],
        faqs: [
            { q: 'Is your PTFE suitable for pharmaceutical use?', a: 'Yes. We supply virgin PTFE grades that are chemically inert, non-toxic and suitable for pharmaceutical manufacturing applications including sealing, lining and fluid handling.' },
            { q: 'Do you provide material certificates for pharma applications?', a: 'Yes. We provide full Material Test Certificates (MTC) with every order to support your quality and compliance documentation requirements.' },
            { q: 'Can you supply custom machined PTFE components?', a: 'Yes. We supply precision custom machined PTFE components as per your engineering drawings and dimensional requirements.' },
            { q: 'What PTFE grades do you recommend for pharma?', a: 'Virgin PTFE is most commonly used in pharmaceutical applications due to its chemical purity and inertness. We can advise on grade selection based on your specific application.' },
            { q: 'What is your MOQ for pharma orders?', a: 'MOQ is negotiable. We work with both small quantity trial orders and large bulk requirements. Contact us to discuss your specific needs.' },
        ],
    },

    'chemical-processing': {
        metaTitle: 'PTFE Products for Chemical Industry | Visanix Global',
        metaDescription: 'Visanix Global supplies PTFE sheets, gaskets, tubes and gland packing for chemical processing plants. Resistant to virtually all acids, alkalis and solvents.',
        h1: 'PTFE Solutions for Chemical Processing Plants',
        tag: 'Chemical Processing',
        heroDescription: 'Corrosion-resistant PTFE materials for the most aggressive chemical processing environments.',
        whyPTFE: 'PTFE is the premier material for chemical processing applications due to its near-universal chemical resistance. As a trusted <strong>PTFE supplier for chemical plants in India</strong>, Visanix Global supplies PTFE sheets, gaskets, tubes, and gland packing — also known as Teflon lining material — for the most aggressive chemical environments. PTFE is resistant to virtually all industrial chemicals including concentrated acids (sulphuric, hydrochloric, nitric, hydrofluoric), strong alkalis, organic solvents, and oxidising agents. This makes PTFE the material of choice for gaskets, linings, seals, and fluid handling components in chemical plants where metal or rubber components would corrode or degrade rapidly. PTFE maintains its chemical resistance across a wide temperature range from -200°C to +260°C, covering the full spectrum of chemical processing conditions. Its low coefficient of friction also reduces wear in dynamic sealing applications such as pump glands and valve stems.',
        compliance: ['ASTM Standards', 'DIN Standards', 'Chemical Resistance to ASTM D543'],
        keyBenefit: 'Resistant to virtually all chemicals including concentrated acids, alkalis and solvents',
        recommendedProducts: [
            { name: 'PTFE Moulded Sheet', href: '/products/ptfe-sheet-moulded', use: 'Tank and vessel lining, structural components' },
            { name: 'PTFE Gasket', href: '/products/ptfe-gasket', use: 'Flange sealing in aggressive chemical pipelines' },
            { name: 'PTFE Tube', href: '/products/ptfe-tube', use: 'Chemical transfer lines and reactor connections' },
            { name: 'PTFE Gland Packing', href: '/products/ptfe-gland', use: 'Pump shaft and valve stem sealing' },
        ],
        faqs: [
            { q: 'Is your PTFE resistant to aggressive chemicals?', a: 'Yes. PTFE is resistant to virtually all industrial chemicals including acids, alkalis and solvents. We supply grades suitable for the most demanding chemical processing environments.' },
            { q: 'What PTFE products are used in chemical plants?', a: 'Commonly used products include PTFE sheets for lining, PTFE gaskets for sealing, PTFE tubes for fluid transfer, and PTFE gland packing for valve sealing.' },
            { q: 'Do you supply filled PTFE grades for chemical applications?', a: 'Yes. We supply glass filled, carbon filled and graphite filled PTFE grades which offer enhanced mechanical properties for chemical processing equipment.' },
            { q: 'Do you provide MTC with chemical grade PTFE?', a: 'Yes. Full Material Test Certificates provided with every order.' },
            { q: 'What is your MOQ for chemical industry orders?', a: 'MOQ is flexible and negotiable. Contact us to discuss your specific volume requirements.' },
        ],
    },

    'oil-and-gas': {
        metaTitle: 'PTFE Components for Oil & Gas Industry | Visanix Global',
        metaDescription: 'Visanix Global supplies high-performance PTFE rings, gland packing, bushes and rods for oil and gas applications. Extreme temperature and pressure resistance.',
        h1: 'High-Performance PTFE for Oil & Gas Applications',
        tag: 'Oil & Gas',
        heroDescription: 'High-pressure, high-temperature PTFE sealing and bearing components for upstream and downstream oil and gas operations.',
        whyPTFE: 'The oil and gas industry demands materials that can withstand extreme temperatures, high pressures, and aggressive hydrocarbon media. As a <strong>PTFE valve seat supplier in India</strong> and <strong>PTFE gland packing supplier for oil and gas</strong>, Visanix Global supplies high-performance PTFE rings, bushes, rods, and gland packing for upstream and downstream operations. PTFE is resistant to crude oil, refined petroleum products, natural gas, hydrogen sulphide, and the wide range of chemicals used in drilling and production operations. Filled PTFE grades (carbon-filled, glass-filled) provide the enhanced mechanical strength and wear resistance required for dynamic sealing applications in downhole tools, wellhead equipment, and surface processing facilities. PTFE back-up rings and seals are standard components in hydraulic and pneumatic systems throughout oil and gas operations, providing reliable sealing performance at pressures up to several thousand PSI.',
        compliance: ['API Standards', 'NACE MR0175 Compatible'],
        keyBenefit: 'Extreme temperature and pressure resistance — suitable for downhole and surface applications',
        recommendedProducts: [
            { name: 'PTFE Ring', href: '/products/ptfe-ring', use: 'Back-up rings and seals for hydraulic systems' },
            { name: 'PTFE Gland Packing', href: '/products/ptfe-gland', use: 'Valve stem and pump shaft sealing' },
            { name: 'PTFE Bush', href: '/products/ptfe-bush', use: 'Bearings in pumps and rotating equipment' },
            { name: 'PTFE Rod', href: '/products/ptfe-rod', use: 'Machined into custom valve and seal components' },
        ],
        faqs: [
            { q: 'What PTFE products do you supply for oil and gas applications?', a: 'We supply PTFE rings, gland packing, bushes and rods commonly used in valves, pumps and sealing applications in oil and gas equipment.' },
            { q: 'Can PTFE handle high temperature and pressure?', a: 'Virgin PTFE operates continuously up to 260°C. Filled grades offer improved mechanical strength under pressure. We can advise on the right grade for your operating conditions.' },
            { q: 'Do you supply custom PTFE components for oil and gas?', a: 'Yes. We supply precision custom machined components as per your engineering drawings and specifications.' },
            { q: 'Do you provide MTC for oil and gas orders?', a: 'Yes. Full Material Test Certificates are provided with every order.' },
            { q: 'What is your MOQ for oil and gas orders?', a: 'MOQ is negotiable based on requirement. Contact us to discuss.' },
        ],
    },

    'food-processing': {
        metaTitle: 'Food Grade PTFE Supplier India | Visanix Global',
        metaDescription: 'Visanix Global supplies FDA food contact approved PTFE tubes, gaskets and sheets for food processing industry. Non-toxic, non-stick, easy to clean.',
        h1: 'FDA Grade PTFE for Food Processing Industry',
        tag: 'Food Processing',
        heroDescription: 'Non-toxic, FDA food contact approved PTFE materials for hygienic food and beverage processing applications.',
        whyPTFE: 'Food processing equipment requires materials that are non-toxic, non-contaminating, easy to clean, and resistant to the wide range of food acids, cleaning chemicals, and sterilisation agents used in production. As a <strong>food grade PTFE supplier in India</strong> and <strong>FDA approved Teflon supplier</strong>, Visanix Global supplies virgin PTFE products that meet all FDA food contact regulations. PTFE — also known as Teflon in food industry applications — is approved for direct contact with food and beverages. Its non-stick surface prevents food product adhesion and bacterial growth, making it ideal for conveyor components, seals, gaskets, and fluid handling parts in food processing lines. PTFE is also resistant to the caustic cleaning agents (CIP/SIP) used in food plant sanitation, ensuring long service life without degradation.',
        compliance: ['FDA Food Contact Approved', 'EU Food Contact Regulation 10/2011', 'NSF Compliant'],
        keyBenefit: 'Non-toxic, non-stick, FDA food contact approved — easy to clean and sterilise',
        recommendedProducts: [
            { name: 'PTFE Tube', href: '/products/ptfe-tube', use: 'Food and beverage fluid transfer lines' },
            { name: 'PTFE Gasket', href: '/products/ptfe-gasket', use: 'Hygienic flange sealing in food pipelines' },
            { name: 'PTFE Skived Sheet', href: '/products/ptfe-sheet-skived', use: 'Conveyor linings and non-stick surfaces' },
        ],
        faqs: [
            { q: 'Is your PTFE food grade safe?', a: 'Yes. Virgin PTFE is FDA recognized as safe for food contact applications. It is non-toxic, non-reactive and does not leach into food products.' },
            { q: 'What PTFE products are used in food processing?', a: 'Commonly used products include PTFE tubes for fluid transfer, PTFE gaskets for sealing, and PTFE sheets for food contact surfaces and conveyor applications.' },
            { q: 'Do you provide food grade certification?', a: 'We provide Material Test Certificates with every order. Contact us to discuss specific certification requirements for your application.' },
            { q: 'What is your MOQ for food grade PTFE?', a: 'MOQ is flexible and negotiable. We cater to both small and bulk orders.' },
            { q: 'Can you supply custom dimensions for food processing equipment?', a: 'Yes. Custom machined PTFE components are available as per your engineering drawings.' },
        ],
    },

    'water-treatment': {
        metaTitle: 'PTFE for Water Treatment Plants | Visanix Global',
        metaDescription: 'Visanix Global supplies PTFE gaskets, tubes and gland packing for water treatment plants. Chemical resistance to chlorine, ozone and treatment chemicals.',
        h1: 'PTFE Solutions for Water Treatment Applications',
        tag: 'Water Treatment',
        heroDescription: 'Chlorine-resistant PTFE sealing and fluid handling components for municipal and industrial water treatment plants.',
        whyPTFE: 'Water treatment plants use aggressive chemicals including chlorine, chloramine, ozone, sodium hypochlorite, and various coagulants and flocculants that rapidly degrade conventional rubber and metal components. PTFE is resistant to all water treatment chemicals, including high concentrations of chlorine and ozone that attack most other materials. This makes PTFE gaskets, seals, and fluid handling components the preferred choice for dosing systems, filter housings, and chemical feed lines in water treatment facilities. PTFE also does not leach any substances into treated water, ensuring compliance with drinking water quality standards. Its long service life in aggressive chemical environments reduces maintenance downtime and replacement costs in water treatment operations.',
        compliance: ['NSF/ANSI 61 Compatible', 'Drinking Water Safe', 'Chlorine Resistant'],
        keyBenefit: 'Chemical resistance to chlorine, ozone and all water treatment chemicals',
        recommendedProducts: [
            { name: 'PTFE Gasket', href: '/products/ptfe-gasket', use: 'Flange sealing in chemical dosing systems' },
            { name: 'PTFE Tube', href: '/products/ptfe-tube', use: 'Chemical feed and dosing lines' },
            { name: 'PTFE Gland Packing', href: '/products/ptfe-gland', use: 'Pump shaft sealing in chemical dosing pumps' },
        ],
        faqs: [
            { q: 'Is PTFE suitable for water treatment applications?', a: 'Yes. PTFE is highly resistant to chlorine, ozone and treatment chemicals used in water treatment plants making it ideal for sealing and fluid handling applications.' },
            { q: 'What PTFE products are used in water treatment?', a: 'Commonly used products include PTFE gaskets, PTFE tubes and PTFE gland packing for pumps and valve sealing in water treatment systems.' },
            { q: 'Do you supply PTFE across India for water treatment projects?', a: 'Yes. We supply PTFE products to water treatment projects across all major cities and states in India.' },
            { q: 'Do you provide MTC for water treatment orders?', a: 'Yes. Full Material Test Certificates provided with every order.' },
            { q: 'What is your MOQ?', a: 'MOQ is negotiable. Contact us to discuss your specific requirement.' },
        ],
    },

    'industrial-manufacturing': {
        metaTitle: 'PTFE for Industrial OEM Manufacturers | Visanix Global',
        metaDescription: 'Visanix Global supplies precision PTFE rods, bushes, rings and custom components for industrial OEM manufacturers. Custom machined to your drawings.',
        h1: 'PTFE Components for Industrial OEM Manufacturing',
        tag: 'Industrial Manufacturing',
        heroDescription: 'Precision-grade PTFE components and custom machined parts for industrial OEM manufacturers across India.',
        whyPTFE: 'Industrial OEM manufacturers require precision-grade engineering materials that can be machined to tight tolerances, maintain dimensional stability under load, and perform reliably in demanding operating conditions. PTFE and filled PTFE grades meet all these requirements. Virgin PTFE provides maximum chemical resistance and electrical insulation. Glass-filled PTFE offers improved stiffness and reduced creep under sustained load. Carbon-filled PTFE provides enhanced wear resistance and thermal conductivity for dynamic sealing applications. Graphite-filled PTFE delivers the lowest coefficient of friction for sliding and bearing surfaces. Visanix Global supplies PTFE rod, sheet, and tube stock for in-house machining, as well as custom machined components manufactured to your drawings and specifications with lead times of 3–7 working days.',
        compliance: ['RoHS Compliant', 'REACH Compliant', 'Custom to Drawing'],
        keyBenefit: 'Precision machined custom components available — supplied to drawing with 3–7 day lead time',
        recommendedProducts: [
            { name: 'PTFE Rod', href: '/products/ptfe-rod', use: 'Machinable stock for custom components' },
            { name: 'PTFE Bush', href: '/products/ptfe-bush', use: 'Self-lubricating bearings for machinery' },
            { name: 'PTFE Ring', href: '/products/ptfe-ring', use: 'Sealing rings for hydraulic and pneumatic systems' },
            { name: 'PTFE Moulded Sheet', href: '/products/ptfe-sheet-moulded', use: 'Machinable blanks for structural components' },
        ],
        faqs: [
            { q: 'Do you supply PTFE for OEM manufacturers?', a: 'Yes. We specifically cater to industrial OEM manufacturers requiring PTFE rods, sheets, tubes and precision machined custom components.' },
            { q: 'Can you supply custom machined PTFE parts as per drawings?', a: 'Yes. We supply precision custom machined PTFE components as per your engineering drawings, CAD files or dimensional specifications.' },
            { q: 'What filled PTFE grades do you supply for industrial use?', a: 'We supply 15% Glass Filled, 25% Glass Filled, 25% Carbon Filled, Carbon + Graphite Filled and 25% Graphite Filled grades offering enhanced wear resistance and mechanical properties.' },
            { q: 'What is your lead time for custom components?', a: 'Lead time for custom machined components is typically 2-4 weeks depending on complexity and quantity. Contact us for a specific timeline.' },
            { q: 'What is your MOQ for industrial orders?', a: 'MOQ is negotiable based on your requirement. We work with both trial and bulk orders.' },
        ],
    },
}
